network = "test"
seed = "SATKBWSRLPHGM2FKMLZ4QNH64XYKP7J2O6U5QNFBJHYEXDSHN75R5MVE"
test_passphrase = "Test SDF Network ; September 2015"
public_passphrase = "Public Global Stellar Network ; September 2015"
db_pool = 4
max_peers = 10
min_peers = 5

[local_node]
ip = "127.0.0.1"
port = 8080

# test
[[initial_peers]]
host = "core-testnet1.stellar.org"

[[initial_peers]]
host = "core-testnet2.stellar.org"

[[initial_peers]]
host = "core-testnet3.stellar.org"

# public
# [[initial_peers]]
# host = "35.234.95.115"

# [[initial_peers]]
# host = "35.247.129.227"

# [[initial_peers]]
# host = "35.194.40.151"

# [[initial_peers]]
# host = "54.204.238.171"
