network = "test"
seed = "SATKBWSRLPHGM2FKMLZ4QNH64XYKP7J2O6U5QNFBJHYEXDSHN75R5MVE"
test_passphrase = "Test SDF Network ; September 2015"
public_passphrase = "Public Global Stellar Network ; September 2015"
db_pool = 4
max_peers = 10
min_peers = 5

[local_node]
ip = "127.0.0.1"
port = 8080

# test
[[initial_peers]]
host = "54.161.82.181"
port = 11625

[[initial_peers]]
host = "54.211.174.177"
port = 11625

[[initial_peers]]
host = "54.160.175.7"
port = 11625

[[initial_peers]]
host = "core-testnet1.stellar.org"
port = 11625

# public
# [[initial_peers]]
# host = "35.234.95.115"
# port = 11625

# [[initial_peers]]
# host = "35.247.129.227"
# port = 11625

# [[initial_peers]]
# host = "35.194.40.151"
# port = 11625

# [[initial_peers]]
# host = "54.204.238.171"
# port = 11625
